### PR TITLE
adding BaseCampMaxNumInGuild option

### LINKED ISSUE #35: New option BaseCampMaxNumInGuild
v0.3.2.55495 supports up to 10 bases, which can be set with the BaseCampMaxNumInGuild option. However, palworld-worldoptions does not recognize this parameter and does not work on the server.

### PR DESCRIPTION
**Pull request by xiahuaijia**
fix https://github.com/legoduded/palworld-worldoptions/issues/35

### CODE REVIEW

**Comment by legoduded** [comment]
Thanks for jumping on this. Is the default for BaseCampMaxNumInGuild 4 now? I know on previous versions it was 3. Sorry I'm a little out of the loop on the most recent update

**Comment by xiahuaijia** [comment]
unlock the fourth base when the base reaches level 25 and you can view the default settings in the `DefaultPalWorldSettings.ini` file. But I haven't tested whether this default value will have any effect when the base is lower than level 25.


> v0.3.2.55495

**Comment by legoduded** [comment]
perfect. I just updated my server and I see the default value as 4

**Comment by CaspyBXL** [comment]
There seems to be an issue, we have lvl 50 players on the server that keep saying they do not see the 4th base option in the palbox available. We updated the server config, and when I create a new character and guild the problem is not there, Is there some way to fix the lvl 50's to have it too ? it seems to not have updated if the setting changes after server already running.

**Pull request merged**
